### ISSUE TITLE
Rerun benchmarks with current versions

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/TestBenchmarks#2]
- Resharper runner
- VS runner parallel & not
- Rider

**Comment by jnm2** [comment]
Would it be easy to include the NUnit console runner for NUnit, and xUnit's for xUnit?

**Comment by JohanLarsson** [comment]
I have never used console runners for anything but guessing it should not be too hard.

**Comment by jnm2** [comment]
Nope! You can script them both with Cake especially easily. Also VSTest.Console.exe.

**Comment by JohanLarsson** [comment]
I'm closing this. Was so bored in the end I did not run using console runners.

**Comment by jnm2** [comment]
That's okay. Gotta script all the things eventually, though. :D I might end up being able to contribute something.
